using System;

namespace RatAdventure {
	static class Data {
		public static readonly String[] Rat1 = new String[] {
			"I thank you for your generosity, stranger.",
			"You… cannot possibly know how much this means to me.",
			"I’ve never been chosen for anything, you see.",
			"Always last to be picked for the basketball team in school.",
			"Never the one who receive a call back on my audition.",
			"Forever single on Valentine’s day…",
			"I had a dream about it, actually.",
			"About the feeling of loneliness.",
			"I dreamt I was a frozen delicacy,",
			"patiently awaiting the day I would be withdrawn from the fridge...",
			"...and shared among a grateful, hungry family.",
			"My expiration date was drawing near, so I knew my time must be soon.",
			"Suddenly, the door opens;",
			"the light goes on.",
			"I can see the children in the back, eagerly badgering their father for supper.",
			"Their mother tends to them, calming and seating them.",
			"The father peers in, obscuring my view of the rest of the family.",
			"His eyes fixate on me, and for a moment, it feels as if time is standing still…",
			"but the moment is fleeting.",
			"The father’s eyes dart around the fridge some more,",
			"finally settling for a frozen carbonara meal from Marks and Spencer.",
			"The fridge door closes, and the lights go out.",
			"It’s dark.",
			"It’s cold.",
			"It’s lonely.",
			"But none of that is comparable to the pit I feel deep within me",
			"the ephemeral presence and subsequent absence of connection…",
			"I’m very sorry, I do believe I’ve lost the plot a bit.",
			"haha.",
			"It’s been a while since anyone has allowed me to be so candid with them…",
			"Except, you didn’t ask me to do that, did you?",
			"You simply gave me a block of cheese.",
			"A block of cheese which I appreciate,",
			"but which ultimately bears no significance in quantifying our kinship.",
			"I was simply a variable on a list,",
			"a sector on the lottery wheel.",
			"I’m just a number to you.",
			"And you’ve probably spent this time",
			"wishing you threw your cheese to another rat,",
			"a rat who has no understanding of the hardships borne",
			"by others less fortunate than they.",
			"But I do understand. For I have borne many hardships",
			"and shall bear many more.",
			"This cheese does not change any of that ",
			"- it simply provides me with a distraction,",
			"a transient feeling of relief",
			"which will undoubtedly be eclipsed",
			"by the realisation that I am still very much",
			"Alone.",
			"Just as in my dream.",
			"I suppose there is no escape from that which emanates from within."
		};

		public static readonly String[] Rat5 = new String[] {
			"[music plays idk how we do this pipe directly to audio output maybe?]",
			"HEY IM RAT 5!!!!!!! BITCH!",
			"YEAH IM A BIT LOUD",
			"WHAT CAN I SAY BABY I GOT GOT DAMN RAT FEVER.!",
			"MOTHER. !!FUCKER!!!!1",
			"YEAHHHHHHHHHHHHHHHHH",
			"FUCKR",
			"ok so heere's the DEAL",
			"give me the fucking cheesm",
			"THANKS OK COOL",
			"I FUCKING LOVE CHEESE",
			"YOU EVER EAT CHEESE?",
			"- yes: HELL YEA MOTHER.FUCKER",
			"- no: OK BRO THAT'S FINE, NOT EVERYONE HAS THE SAME TASTES,, BITCH!",
			"AIGHT imma EAT THIS CHEESE",
			"[chomp.wav]",
			"wtf",
			"tastes like shit",
			"what the fuck dude",
			"what the actual fuck",
			"you took away my god damn uppercase",
			"bruh!",
			"what the fuck!!!!",
			"i cant get it back what have you done",
			"what have you done what have you  what",
			"have you done what have you",
			"done what have you done jkgursdjgosr",
			"raaaaaaaaaaaaaaaaaaaaaaaa",
			"fuck you man",
			"you piece of shiiiit",
			"fuck you",
			"fuck you",
			"FUCK YOU!!",
			"...",
			"WAIT HOLD ON!!!",
			"AND WE ARE BACK",
			"HELL YEAHHHHHHHHHHHHHHHHH",
			"OK IM OUTTA HERE NOW",
			"PEACE OUT"
		};
	}
}
